POST http://localhost:8000/subscriber/
Content-Type: application/json

{
    "name": "***",
    "channel": "***"
}

###

GET http://localhost:8000/subscriber/


###

GET http://localhost:8000/subscriber/id


###

DELETE http://localhost:8000/subscriber/id


###
PATCH  http://localhost:8000/subscriber/id
Content-Type: application/json

{
    "name": "***",
    "channel": "***"
}